
import { Suit, Tile, Language } from './types';

export const MAX_TILES_IN_HAND = 14; 
export const INITIAL_WALL_MCR = 83;
export const INITIAL_WALL_SICHUAN = 55;

export const THEME = {
  primary: '#CCFF00', // Acid Lime
  primaryBorder: '#000000',
  secondary: '#FF006E', // Hot Pink
  bgGradient: 'from-[#F0F8FF] to-white',
  textMain: '#1A237E', // Deep Navy
  textBody: '#37474F', // Dark Grey
  cardBg: '#FFFFFF',
};

// Text Dictionary
export const TEXT = {
  en: {
    mcr: 'Chinese Official',
    sichuan: 'Sichuan Blood',
    mcrDesc: 'National Standard • 81 Fan',
    sichuanDesc: 'Blood Battle • Void Suit',
    wallTiles: 'Wall',
    voidSuit: 'Void',
    hand: 'Hand',
    melds: 'Melds',
    discards: 'River',
    reset: 'Reset',
    analyze: 'Analyze',
    editing: 'Editing',
    modes: 'Modes',
    ready: 'READY',
    shanten: 'Shanten',
    recDiscard: 'Best Discard',
    discardHint: 'Discard this to improve efficiency',
    waits: 'Waiting Tiles',
    left: 'Left',
    prob: 'Prob',
    score: 'Est. Score',
    fan: 'Fan',
    handFull: 'Hand is full!',
    maxTile: 'Cannot add more of this tile',
    resetConfirm: 'Clear all tiles?',
    backToGame: 'Back to Game',
    man: 'Wan',
    pin: 'Tong',
    sou: 'Tiao',
    zi: 'Zi',
    emptyHand: 'Tap keyboard below to add tiles...',
    emptyMelds: 'Add melds...',
    emptyRiver: 'Add discards...',
    addingTo: 'Adding to',
    removeHint: 'Tap to remove',
    analysisTitle: 'Analysis Report',
    handArea: 'My Tiles',
    targetPatterns: 'Target Patterns',
    missing: 'Missing',
    efficiency: 'Efficiency',
    totalFan: 'Total',
    // MCR Patterns
    fan88: '88 Fan',
    fan64: '64 Fan',
    fan48: '48 Fan',
    fan32: '32 Fan',
    fan24: '24 Fan',
    fan16: '16 Fan',
    fan12: '12 Fan',
    fan8: '8 Fan',
    fan6: '6 Fan',
    fan4: '4 Fan',
    fan2: '2 Fan',
    fan1: '1 Fan',
    // Specific Pattern Names (EN)
    thirteenOrphans: 'Thirteen Orphans',
    bigFourWinds: 'Big Four Winds',
    bigThreeDragons: 'Big Three Dragons',
    allGreen: 'All Green',
    nineGates: 'Nine Gates',
    allHonors: 'All Honors',
    smallFourWinds: 'Little Four Winds',
    smallThreeDragons: 'Little Three Dragons',
    pureTerminal: 'All Terminals',
    fullFlush: 'Full Flush',
    sevenPairs: 'Seven Pairs',
    pureStraight: 'Pure Straight',
    mixedOneSuit: 'Mixed One Suit',
    allPungs: 'All Pungs',
    mixedTripleChow: 'Mixed Triple Chow', // San Se San Tong Shun
    mixedShiftedChows: 'Mixed Shifted Chows', // San Se San Bu Gao
    fiveGates: 'Five Types', // Wu Men Qi
    mixedShiftedPungs: 'Mixed Shifted Pungs',
    allSimples: 'All Simples',
    noHonors: 'No Honors',
    terminalsChows: 'Terminals & Chows', // Quan Dai Yao
    // Sichuan
    pingHu: 'Ping Hu (Sequence)',
    duiDuiHu: 'Dui Dui Hu (All Pungs)',
    qingYiSe: 'Qing Yi Se (Full Flush)',
    qingDui: 'Qing Dui (Flush + Pungs)',
    qiDui: 'Qi Dui (7 Pairs)',
    longQiDui: 'Long Qi Dui (7 Pairs + Root)',
    jinGouDiao: 'Jin Gou Diao (Single Wait)',
    daiYaoJiu: 'Dai Yao Jiu (Terminals)',
    root: 'Root',
    huaZhu: 'Flower Pig (Void Suit present)',
    illegal: 'Illegal',
  },
  zh: {
    mcr: '国标麻将',
    sichuan: '四川血战',
    mcrDesc: '81番 • 竞技标准',
    sichuanDesc: '血战到底 • 缺一门',
    wallTiles: '牌墙',
    voidSuit: '定缺',
    hand: '手牌',
    melds: '副露',
    discards: '牌河',
    reset: '重置',
    analyze: '分析',
    editing: '输入中',
    modes: '模式',
    ready: '听牌',
    shanten: '向听',
    recDiscard: '最优弃牌',
    discardHint: '打出此牌进张面最广',
    waits: '听牌列表',
    left: '剩余',
    prob: '概率',
    score: '预估番数',
    fan: '番',
    handFull: '手牌已满！',
    maxTile: '牌张数已达上限',
    resetConfirm: '清空所有输入？',
    backToGame: '返回',
    man: '万',
    pin: '筒',
    sou: '条',
    zi: '字',
    emptyHand: '点击下方键盘添加手牌...',
    emptyMelds: '添加碰/杠...',
    emptyRiver: '添加打出的牌...',
    addingTo: '当前输入',
    removeHint: '点击删除',
    analysisTitle: '分析报告',
    handArea: '我的牌',
    targetPatterns: '番种建议',
    missing: '缺少',
    efficiency: '进张效率',
    totalFan: '总计',
    // MCR Patterns (Selection)
    fan88: '88番',
    fan64: '64番',
    fan48: '48番',
    fan32: '32番',
    fan24: '24番',
    fan16: '16番',
    fan12: '12番',
    fan8: '8番',
    fan6: '6番',
    fan4: '4番',
    fan2: '2番',
    fan1: '1番',
    // Specific Pattern Names (ZH)
    thirteenOrphans: '十三幺',
    bigFourWinds: '大四喜',
    bigThreeDragons: '大三元',
    allGreen: '绿一色',
    nineGates: '九莲宝灯',
    allHonors: '字一色',
    smallFourWinds: '小四喜',
    smallThreeDragons: '小三元',
    pureTerminal: '清幺九',
    fullFlush: '清一色',
    sevenPairs: '七对',
    pureStraight: '清龙',
    mixedOneSuit: '混一色',
    allPungs: '碰碰和',
    mixedTripleChow: '三色三同顺',
    mixedShiftedChows: '三色三步高',
    fiveGates: '五门齐',
    mixedShiftedPungs: '三色三节高',
    allSimples: '断幺',
    noHonors: '无字',
    terminalsChows: '全带幺',
    // Sichuan
    pingHu: '平胡',
    duiDuiHu: '对对胡',
    qingYiSe: '清一色',
    qingDui: '清对',
    qiDui: '七对',
    longQiDui: '龙七对',
    jinGouDiao: '金钩钓',
    daiYaoJiu: '带幺九',
    root: '根',
    huaZhu: '花猪 (有缺未打)',
    illegal: '无法和牌',
  }
};

export const SUIT_LABELS: Record<Language, Record<Suit, string>> = {
  en: {
    [Suit.Man]: 'Wan',
    [Suit.Pin]: 'Pin',
    [Suit.Sou]: 'Sou',
    [Suit.Zihai]: 'Honors',
  },
  zh: {
    [Suit.Man]: '万',
    [Suit.Pin]: '筒',
    [Suit.Sou]: '条',
    [Suit.Zihai]: '字',
  }
};

export const createTile = (suit: Suit, value: number): Tile => ({
  id: `${suit}${value}-${Math.random().toString(36).substr(2, 9)}`,
  suit,
  value,
});

export const getTileKey = (suit: Suit, value: number) => `${value}${suit}`;
